### ISSUE TITLE
example project error

### ISSUE THREAD

**Issue by emirbeytekin** [gonzalonunez/GNCam#2]
Example project not working. I change your BG3Y5KSHNC key, install and run app but camera screen is not working.

**Comment by gonzalonunez** [comment]
Hello!

I'm going to take a look at this now. By making a fresh project. If you can also let me know what the specific problem is, that would help.

As a note, the camera will not work on the simulator.

**Comment by emirbeytekin** [comment]
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
(lldb)

**Comment by gonzalonunez** [comment]
Ok good, now we know! Totally forgot to add that in the sample project. Let me:
- Add that now
- Update the pod
- Clarify that in the documentation

My apologies!

**Comment by gonzalonunez** [comment]
Updated! Let me know if all is good now 🙂
