### ISSUE TITLE
Multiple images taken like the original giffy project 

### ISSUE THREAD

**Issue by jackpaster** [gonzalonunez/GNCam#3]
@gonzalonunez I love your project very much, but I'm having a problem. Instead of taking one photo and presenting the next viewcontroller the image. I want the user to hold down on the enticer button and a burst of images will be taken until they let go of the camera button. Once the user lets go, the enticer button stops animating. Once they let go, the array of images taken will be passed onto the next view controller. Can you please implement this

**Comment by jackpaster** [comment]
@gonzalonunez ive tried working with your project, but I'm stuck. Ive been bashing head because I can't figure out what to do. I really need your help.

**Comment by gonzalonunez** [comment]
Hey! This is absolutely possible. You have essentially three options, two of which I use in Giffy. I'm going to say them off the top of my head but I think they'll be clear enough:

1) Inside the completion block, you can simply set off a timer to call the same method again after some time and cancel it if the user takes their finger off the top. This would be for the slowest most separated burst mode.

2) You can use the VideoDataOutputDelegate instead (simply add .videoData as an output of your CaptureManager and set yourself as the delegate when the user holds down the button, set it to the nil when they lift a finger or have that flag inside the delegate method itself). Inside this method, you can simply keep track of how many frames have come in and choose one every _x_ frames. Every time you pick one, you convert this sample buffer to a UIImage (you can find that code in my other library, Walt). This will leave you with a fast or slow burst depending on your _x_.

3) If you want a burst just like the iPhone's burst mode, I'm _pretty sure_ there's a method for that now that works on certain devices and after a certain iOS version. If this is what you want, you can look at the docs to find this method and try extending CaptureManager or I can add that to the library in a couple of weeks.

**Comment by jackpaster** [comment]
@gonzalonunez thanks. But you split huffy into three separate github project. Do you have one GitHub project that has gncamera, the tickerbutton, and Walt in one whole workspace. Because I'm having trouble putting these prices in one project that could help achieve my outcome. And yes, please can you add the library.

**Comment by jackpaster** [comment]
@gonzalonunez never mind you don't have to add the library. But which one of the options you told me about will allow me to not only put a limit on the number of photos that can be taken in the burst(like the one in giffy). Or when the user takes his finger off the button before the limit has been reached, then a new view controller will pop up with all of the images in an image array.

**Comment by jackpaster** [comment]
@gonzalonunez do you have the full giffy project you can share with me. It's exactly what I'm looking for. You have the project on github but it's in parts and prices. Do you think you could do that

**Comment by gonzalonunez** [comment]
Hey Jack, I just answered your email. Let me know if that helps a little more :)
