### ISSUE TITLE
Opening cam with UINavigationController NavigationBar

### ISSUE THREAD

**Issue by erkanatesli** [gonzalonunez/GNCam#4]
Hi Gonzales,

Is there a possibilty to start the Camera with showing my UINavigationBar at the top?
I've a application where i start with a UINavigationController stack and as a rootcontroller my CameraController. Inside this i use now your example like present but this is opening in a new fullscreen composition.

Many thanks.
Erkan

**Comment by gonzalonunez** [comment]
Yes that's absolutely possible! Have you checked that your `UINavigationController`'s `isNavigationBarHidden` (or the animated equivalent) is set to `false`?

**Comment by erkanatesli** [comment]
Hi Gonzales,

My NavigationBar is showing. There is no issue's with that. Only when i start the GNCam controller with "present(.... " then it will show it on fullscreen. I've not set any navigationbar to hidden or something. It is opening above my navigationcontroller/bar.  What i want is to see my navigationbar even when the camera is turned on.

**Comment by gonzalonunez** [comment]
You will need to embed `CaptureViewController` within a `UINavigationController` as well then:

```swift
let captureViewController = ...
let navigationController = UINavigationController(rootViewController: captureViewController)
```

And now you present `navigationController` instead.

**Comment by erkanatesli** [comment]
Yeah i've tried that that is working. But you have to be already on a UINavigationController stack to do that. 
If i present the new UINavigationController with as rootController the captureViewController, it will create a new NavigationBar. My original Navigationbar is behind this which will be not used. Can i use the first UINavigationController initialized ( in storyboard) ? I thought something like to do the rootController as captureViewController where 'present' should be changed with something else where the camera will start in that viewcontroller, already stacked in a UINavigationController.

**Comment by gonzalonunez** [comment]
In that case go ahead and change the custom class from within the Storyboard (on the right hand panel under the little File icon). Then make sure to make your `UIViewController` a `CaptureViewController` in the code.

Google how to do this if you need to 👍🏻

**Comment by erkanatesli** [comment]
Gonzales,

This is also working but, the fact that you are now not able to refer to a delegate inside your viewcontroller is missing. Maybe your previous solution was better. Any way, also the buttons for flash, turn camera etc, are now behind the UINavigationBar. Is there any option to re' frame the camera and buttons within a specific size and position?

**Comment by gonzalonunez** [comment]
This should not change anything with regards to delegation and etc. I'm not sure what you mean there.

If you set the `UINavigationBar` to be non-translucent, you'll get the underlying `view` to be under the `UINavigationBar`. On a related tangent, can also hide the close button if you don't need it.

**Comment by gonzalonunez** [comment]
If you want a completely custom solution, feel free to make your own `UIViewController` and just copy the relevant code that's inside of `CaptureViewController`.

**Comment by erkanatesli** [comment]
Many thanks. I will try out something now.

Is there also an option to take a picture with the volume buttons?

**Comment by gonzalonunez** [comment]
That's not included within the framework, but you can easily add that functionality and call the capture function that's within GNCam.

**Comment by erkanatesli** [comment]
Yes i've build it in already. Thnx

**Comment by gonzalonunez** [comment]
No prob – gonna close this issue. Cheers!
