### ISSUE TITLE
Connect VideoDataOutputDelegate

### ISSUE THREAD

**Issue by ghost** [gonzalonunez/GNCam#5]
Hi, how to connect VideoDataOutputDelegate?
It isnt work...

I trying:
 fileprivate lazy var captureController: CaptureViewController = {
        let controller = CaptureViewController(inputs: [.video], outputs: [.stillImage, .metadata([AVMetadataObjectTypeQRCode])])
        controller.captureDelegate = self
        controller.captureManager.dataOutputDelegate = self
        
        return controller
    }()

Please help

**Comment by gonzalonunez** [comment]
Hey! Let me check up on this. I just realized I didn't expose that delegate directly through `CaptureViewController`.

**Comment by gonzalonunez** [comment]
Hey @ronysteel, so the problem is that `.videoData` is missing from your `CaptureViewController`'s outputs. Add that in your initializer and you should be good to go!

Soon, I'm going to go ahead and change the implementation to fix this bug though! I'll leave the issue open until I ship the changes.

**Comment by ghost** [comment]
@gonzalonunez , I added it, bu isn't work.

> open var outputs = [CaptureSessionOutput.videoData, CaptureSessionOutput.stillImage] {
>         didSet {
>             didChangeInputsOrOutputs()
>         }
>     }


> after that I added /// captureManager.dataOutputDelegate = self in my controller, 

// MARK: - VideoDataOutputDelegate

extension CameraViewController: VideoDataOutputDelegate {
    

>     func captureManagerDidOutput(_ sampleBuffer: CMSampleBuffer) {
>         print(1)
>     }
> }
    

... Nothing

**Comment by gonzalonunez** [comment]
Hey! So, I've confirmed that the following works:

```swift
  private lazy var captureVC: CaptureViewController = {
    let vc = CaptureViewController(inputs: [.video], outputs: [.videoData])
    vc.captureManager.dataOutputDelegate = self
    return vc
  }()

  //MARK: VideoDataOutputDelegate
  
  func captureManagerDidOutput(_ sampleBuffer: CMSampleBuffer) {
    print("\(Date()) received sample buffer...")
  }
```

Does this work for you? Let me know 🙂

**Comment by ghost** [comment]
Thank you)) nice work)

**Comment by gonzalonunez** [comment]
No prob! Just FYI, among other things, I'll be changing how the input/outputs work (by adding associated values) to make sure that delegates are provided when necessary at the time you decide to add a particular input or output.

Thanks for you patience!
